<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>C:\Users\joao\source\repos\Sistema-de-Vendas</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Clientes\Events\" />
    <Folder Include="Clientes\ValueObjects\" />
  </ItemGroup>

</Project>
