<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>C:\Users\joao\source\repos\Sistema-de-Vendas</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.cs" />
    <Compile Include="Common\Base\AggregateRoot.cs" />
    <Compile Include="Common\Base\Entity.cs" />
    <Compile Include="Common\Base\ValueObject.cs" />
    <Compile Include="Common\Enums\EstadoCivil.cs" />
    <Compile Include="Common\Enums\MetodoPagamento.cs" />
    <Compile Include="Common\Enums\Sexo.cs" />
    <Compile Include="Common\Enums\StatusPagamento.cs" />
    <Compile Include="Common\Enums\StatusPedido.cs" />
    <Compile Include="Common\Exceptions\DomainException.cs" />
    <Compile Include="Common\Validations\Guard.cs" />
    <Compile Include="Entities\ItemPedido.cs" />
    <Compile Include="Entities\Pagamento.cs" />
    <Compile Include="Events\DomainEventBase.cs" />
    <Compile Include="Events\IDomainEvent.cs" />
    <Compile Include="Events\PagamentoAprovadoEvent.cs" />
    <Compile Include="Events\PagamentoRejeitadoEvent.cs" />
    <Compile Include="Events\PedidoCanceladoEvent.cs" />
    <Compile Include="Events\PedidoEntregueEvent.cs" />
    <Compile Include="Events\PedidoEnviadoEvent.cs" />
    <Compile Include="ValueObjects\EnderecoEntrega.cs" />
    <Compile Include="ValueObjects\MotivoCancelamento.cs" />
  </ItemGroup>

</Project>
