<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vendas.Domain\Vendas.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\ClientesCommands\CriarCliente\" />
    <Folder Include="Commands\ClientesCommands\AtualizarPerfilCliente\" />
    <Folder Include="Commands\ClientesCommands\BloquearCliente\" />
    <Folder Include="Commands\ClientesCommands\AtivarCliente\" />
    <Folder Include="Commands\ClientesCommands\AdicionarEnderecoAoCliente\" />
    <Folder Include="Commands\ClientesCommands\AlterarEnderecoDoCliente\" />
    <Folder Include="Commands\ClientesCommands\DefinirEnderecoPrincipal\" />
    <Folder Include="Commands\ClientesCommands\RemoverEnderecoDoCliente\" />
  </ItemGroup>

</Project>
